server:
  #端口号
  port: 80
  #项目名，如果不设定，默认是 /
 # context-path: /vote
  
 #http://www.cnblogs.com/bigdataZJ/p/springboot-log.html
logging:
  #日志存储地址
  file: logs/config/reptiles.log
  level:
 #   sun: warn
 #   orgSpringframework: info
 #  root: debug
   com.reptile: INFO
   
#logging.pattern.console=%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n 
#logging.pattern.file=%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n
info:
  name: "入门案例"

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.reptile.entity
  mapperLocations: classpath:mapper/*.xml
#  configuration: 
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
 # configLocation: classpath:/mybatis/mybatis-config.xml
  
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
#mybatis:
#  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.winter.model  # 注意：对应实体类的路径
#  configLocation: classpath:mybatis-config.xml



#开发配置
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/test
    url: jdbc:mysql://106.2.11.94:3306/zz_wechat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 123&456
    driver-class-name: com.mysql.cj.jdbc.Driver
 # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-on-borrow: true
      test-while-idle: true
      initial-size: 2
      min-idle: 3
  

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
    
    
    

WEB_URL: http://weixin.sogou.com/weixin
WEB_ENCODER: utf-8
#type=2&ie=utf8&query=机器人发展产业&tsn=5&ft=2018-12-15&et=2018-12-15&interation=&wxid=&usip=
WEB_CONDITION: usip=&ft=&tsn=2&et=&interation=&type=2&wxid=&ie=utf8
#ARTICLE_COOKIE: ABTEST=8|1544153475|v1; SUID=BA014BDA3F18960A000000005C09E983; SUV=00983DF2DA4B01BA5C09E98331DBF551; weixinIndexVisited=1; ppinf=5|1544160292|1545369892|dHJ1c3Q6MToxfGNsaWVudGlkOjQ6MjAxN3x1bmlxbmFtZToxODolRTQlQkUlOUQlRTYlOTclQTd8Y3J0OjEwOjE1NDQxNjAyOTJ8cmVmbmljazoxODolRTQlQkUlOUQlRTYlOTclQTd8dXNlcmlkOjQ0Om85dDJsdU1kbmsxVVdseWNjQ043Wkk5cGFaa1lAd2VpeGluLnNvaHUuY29tfA; pprdig=Fk8563UwtL1H3TTYQHewEGp41ihR84TGUCkHUcRfdLAZBXdff0tvxijOtdo8YNNGH7Ya--G34uH131XvItps99f-8pRvnV-Z5vYtITX5BF7yMGOpUNmxbIcVeUVW3i4VGeUOivdk0nZndixDNS3sB44pmiAoBojjndcow3Y6U1Q; sgid=03-36145051-AVwKBCRUFicJKZgGVUUV6ibww; CXID=15364FC0B482DDF7C561E62E2FB651CE; ad=7Zllllllll2tjXkelllllVZ3WR9lllllL67xmkllll9lllllxCxlw@@@@@@@@@@@; SUID=BA014BDA3118960A000000005C09E983; IPLOC=CN3301; SNUID=6354390FB9BDC449D34AC398B9438923; JSESSIONID=aaaRegtDbdShldgD2H-Cw; ppmdig=1544881373000000a09463599aa6e86a64a6d5aaa44532f0; sct=20
#WEB_COOKIE: ABTEST=8|1544153475|v1; SUID=BA014BDA3F18960A000000005C09E983; SUV=00983DF2DA4B01BA5C09E98331DBF551; weixinIndexVisited=1; ppinf=5|1544160292|1545369892|dHJ1c3Q6MToxfGNsaWVudGlkOjQ6MjAxN3x1bmlxbmFtZToxODolRTQlQkUlOUQlRTYlOTclQTd8Y3J0OjEwOjE1NDQxNjAyOTJ8cmVmbmljazoxODolRTQlQkUlOUQlRTYlOTclQTd8dXNlcmlkOjQ0Om85dDJsdU1kbmsxVVdseWNjQ043Wkk5cGFaa1lAd2VpeGluLnNvaHUuY29tfA; pprdig=Fk8563UwtL1H3TTYQHewEGp41ihR84TGUCkHUcRfdLAZBXdff0tvxijOtdo8YNNGH7Ya--G34uH131XvItps99f-8pRvnV-Z5vYtITX5BF7yMGOpUNmxbIcVeUVW3i4VGeUOivdk0nZndixDNS3sB44pmiAoBojjndcow3Y6U1Q; sgid=03-36145051-AVwKBCRUFicJKZgGVUUV6ibww; CXID=15364FC0B482DDF7C561E62E2FB651CE; ad=7Zllllllll2tjXkelllllVZ3WR9lllllL67xmkllll9lllllxCxlw@@@@@@@@@@@; SUID=BA014BDA3118960A000000005C09E983; IPLOC=CN3301; SNUID=6354390FB9BDC449D34AC398B9438923; JSESSIONID=aaaRegtDbdShldgD2H-Cw; ppmdig=1544881373000000a09463599aa6e86a64a6d5aaa44532f0; sct=20
ARTICLE_COOKIE: ABTEST=0|1545024878|v1; SNUID=C07831A37A7C074B59775B087AC6ABBE; IPLOC=CN3310; SUID=BA014BDA4018960A000000005C17356E; SUID=BA014BDA3118960A000000005C17356F; weixinIndexVisited=1; SUV=00503DF0DA4B01BA5C173572C5D45569; sct=2; ppinf=5|1545028628|1546238228|dHJ1c3Q6MToxfGNsaWVudGlkOjQ6MjAxN3x1bmlxbmFtZToyNzolRTYlOUQlQTglRTYlOTklOTMlRTUlODclQTF8Y3J0OjEwOjE1NDUwMjg2Mjh8cmVmbmljazoyNzolRTYlOUQlQTglRTYlOTklOTMlRTUlODclQTF8dXNlcmlkOjQ0Om85dDJsdVAzc2U5TkpOOGxjRy02dXAzeUNnLVFAd2VpeGluLnNvaHUuY29tfA; pprdig=RMzxbGWcI_xHEu8sDS2c71P3WLjGAqP9lPZ4QYSojjL8ApC7FcHz02QYln0ioQPixrKptNR4dFhToD7SdKHK21BWucwe8s2hc3pWgU7GW-NYGRYsPvhDjQbslsQ94v5c1YqBHfttu47aIcOfDC6kUlB2908byjDTQubBj06tZ3c; sgid=25-38031237-AVwXRBQIiae6L1GiaXlpiaZ6VI; ppmdig=15450327290000003a4e7e90d687e2bde7f92fa99723f7e1; JSESSIONID=aaad8ORQVzqvg-_cAcaDw
WEB_COOKIE: ABTEST=0|1545024878|v1; SNUID=C07831A37A7C074B59775B087AC6ABBE; IPLOC=CN3310; SUID=BA014BDA4018960A000000005C17356E; SUID=BA014BDA3118960A000000005C17356F; weixinIndexVisited=1; SUV=00503DF0DA4B01BA5C173572C5D45569; sct=2; ppinf=5|1545028628|1546238228|dHJ1c3Q6MToxfGNsaWVudGlkOjQ6MjAxN3x1bmlxbmFtZToyNzolRTYlOUQlQTglRTYlOTklOTMlRTUlODclQTF8Y3J0OjEwOjE1NDUwMjg2Mjh8cmVmbmljazoyNzolRTYlOUQlQTglRTYlOTklOTMlRTUlODclQTF8dXNlcmlkOjQ0Om85dDJsdVAzc2U5TkpOOGxjRy02dXAzeUNnLVFAd2VpeGluLnNvaHUuY29tfA; pprdig=RMzxbGWcI_xHEu8sDS2c71P3WLjGAqP9lPZ4QYSojjL8ApC7FcHz02QYln0ioQPixrKptNR4dFhToD7SdKHK21BWucwe8s2hc3pWgU7GW-NYGRYsPvhDjQbslsQ94v5c1YqBHfttu47aIcOfDC6kUlB2908byjDTQubBj06tZ3c; sgid=25-38031237-AVwXRBQIiae6L1GiaXlpiaZ6VI; ppmdig=15450327290000003a4e7e90d687e2bde7f92fa99723f7e1; JSESSIONID=aaad8ORQVzqvg-_cAcaDw


USER_AGENT: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.23 Safari/537.36

#插入文章
TASK_TIME: 0 0/2 * * * ?
#文章概要扫描
ArticleTask: 0 0 0 1/2 * ?
#定时更新ip
setIpPost: 0 0 7,15,23 * * ? 
