server:
  #端口号
  port: 80
  #项目名，如果不设定，默认是 /
 # context-path: /vote
  
 #http://www.cnblogs.com/bigdataZJ/p/springboot-log.html
logging:
  #日志存储地址
  file: E:/logs/config/reptiles.log
  level:
 #   sun: warn
 #   orgSpringframework: info
 #  root: debug
   com.reptile.service: INFO
   com.reptile.task: INFO
   
#logging.pattern.console=%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n 
#logging.pattern.file=%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n
info:
  name: "入门案例"

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.reptile.entity
  mapperLocations: classpath:mapper/*.xml
#  configuration: 
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
 # configLocation: classpath:/mybatis/mybatis-config.xml
  
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
#mybatis:
#  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.winter.model  # 注意：对应实体类的路径
#  configLocation: classpath:mybatis-config.xml



#开发配置
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/test
    url: jdbc:mysql://106.2.11.94:3306/zz_wechat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 123&456
    driver-class-name: com.mysql.cj.jdbc.Driver
 # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
    
    
    

WEB_URL: http://weixin.sogou.com/weixin
WEB_ENCODER: utf-8
WEB_COOKIE: ABTEST=3|1543974603|v1; IPLOC=CN3310; SUID=BA014BDA4018960A000000005C072ECB; SUID=BA014BDA3118960A000000005C072ECB; weixinIndexVisited=1; SUV=000C3DE0DA4B01BA5C072ECC448AB695; SNUID=3880CA5B8284FDBD56BC53148234889E; sct=11; td_cookie=3793477796; ppinf=5|1544151103|1545360703|dHJ1c3Q6MToxfGNsaWVudGlkOjQ6MjAxN3x1bmlxbmFtZToxODolRTQlQkUlOUQlRTYlOTclQTd8Y3J0OjEwOjE1NDQxNTExMDN8cmVmbmljazoxODolRTQlQkUlOUQlRTYlOTclQTd8dXNlcmlkOjQ0Om85dDJsdU1kbmsxVVdseWNjQ043Wkk5cGFaa1lAd2VpeGluLnNvaHUuY29tfA; pprdig=FeOjayEfjciz50eAj-4VPmprjY1w-VhDqUpgjQsd0w-zOH2uZY5pvL0sG3jPSPFsZ5-2TKLPPoNWZxZYIjqCcnTNVSsVv5M-p3HOsDB5GXtj4WJH-vf2ZNOcEMghPs6VVv7_v2yuhIt6pg-NvfN4LXDYVnJ14QDF5bGtWO6loXk; sgid=03-36145051-AVwJ4DibicLM3GwicRqTxEjxWM; ppmdig=154415307500000083dd74f509e4e658b9c1532f559bf451
USER_AGENT: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.23 Safari/537.36
#TASK: 5000 https://blog.csdn.net/xinyuan_java/article/details/51602088
#[秒] [分] [小时] [日] [月] [周] [年]  0/5 * * * * ?
#@Scheduled(fixedRate = 5000) 开始后
#@Scheduled(fixedDelay = 50000)结束后
#@Scheduled(initialDelay = 50000,fixedRate = 6000)延迟后按结束后
TASK_TIME: 0 0/3 * * * ?
ArticleTask: 0 30 22 * * ?
setIpPost: 0 0 12 * * ?
